### ISSUE TITLE
keystone pack

### ISSUE THREAD

**Issue by bucanero** [ps4keystones/ps4keystones.github.io#1]
Hello,

Would it be ok if I include this keystone pack in the next [Apollo Save Tool](https://github.com/bucanero/apollo-ps4) PS4 release?

Apollo can already import/export keystones, and having a keystone database could be useful for many users.

**Comment by ps4keystones** [comment]
[Permission granted here](https://www.reddit.com/r/keystones/comments/hv0u9z/official_rkeystones_mirror/ilre4v5/)
